/* USER CONSTANTS FOR AUTHENTICATION */

export const USER_REQUEST_AUTH = 'USER_REQUEST_AUTH';
export const USER_SUCCESS_AUTH = 'USER_SUCCESS_AUTH';
export const USER_INVALID_AUTH = 'USER_INVALID_AUTH';

export const SIGN_OUT_USER = 'SIGN_OUT_USER';