export const INIT_REQUEST = 'INIT_REQUEST';
export const INIT_SUCCESS = 'INIT_SUCCESS';
export const INIT_INVALID = 'INIT_INVALID';

/* USER CONSTANTS FOR AUTHENTICATION */

export const USER_REQUEST_AUTH = 'USER_REQUEST_AUTH';
export const USER_SUCCESS_AUTH = 'USER_SUCCESS_AUTH';
export const USER_INVALID_AUTH = 'USER_INVALID_AUTH';

export const SIGN_OUT_USER = 'SIGN_OUT_USER';

/* USER MAIN CONSTANTS */

export const USER_REQUEST_INFO = 'USER_REQUEST_INFO';
export const USER_SUCCESS_INFO = 'USER_SUCCESS_INFO';
export const USER_INVALID_INFO = 'USER_INVALID_INFO';

/* USER CONSTANTS FOR CARDS */

export const CARDS_USER_REQUEST = 'CARDS_USER_REQUEST';
export const CARDS_USER_SUCCESS = 'CARDS_USER_SUCCESS';
export const CARDS_USER_INVALID = 'CARDS_USER_INVALID';

/* CONSTANTS FOR CARDS */

export const CARD_INFO_REQUEST = 'CARD_INFO_REQUEST';
export const CARD_INFO_SUCCESS = 'CARD_INFO_SUCCESS';
export const CARD_INFO_INVALID = 'CARD_INFO_INVALID';

/* CONSTANTS FOR SHOPS */

export const SHOPS_LIST_REQUEST = 'SHOPS_LIST_REQUEST';
export const SHOPS_LIST_SUCCESS = 'SHOPS_LIST_SUCCESS';
export const SHOPS_LIST_INVALID = 'SHOPS_LIST_INVALID';

/* CONSTANTS FOR SHOP */

export const SHOP_INFO_REQUEST = 'SHOP_INFO_REQUEST';
export const SHOP_INFO_SUCCESS = 'SHOP_INFO_SUCCESS';
export const SHOP_INFO_INVALID = 'SHOP_INFO_INVALID';